/*
 * Goal Pool API
 *
 * Internal API for my personal project. This API handles operations for a fantasy hockey app that solely tracks goals.
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package api

// Request sent when drafting a player to a team.
type DraftPlayerRequest struct {
	// ID of the team the player is drafted by.
	TeamId float64 `json:"teamId"`
	// ID of the player being drafted.
	PlayerId float64 `json:"playerId"`
}
