/*
 * Goal Pool API
 *
 * Internal API for my personal project. This API handles operations for a fantasy hockey app that solely tracks goals.
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package main

import (
	"log"
	"net/http"

	"github.com/McMastS/nhl-goal-pool/api"
)

func main() {
	log.Printf("Server started")

	router := api.NewRouter()

	log.Fatal(http.ListenAndServe(":8080", router))
}
